### ISSUE TITLE
Unable to upload to gdrive

### ISSUE THREAD

**Issue by johnpatrick9** [biplobsd/Google-Colab-CloudTorrent#10]
hello,whenever I download a torrent file on simple torrent it doesn't seem to be uploading to gdrive could you please fix this? @biplobsd

**Comment by biplobsd** [comment]
In latest version DoneCmd is blocked for security considerations. [[Read more](https://github.com/boypt/simple-torrent/wiki/Config-File#config-on-the-fly)] That's why doesn't working.

But you can install old version and work again past working. 
when first run simple-torrent cell just tick `Install_old_version:`

**Comment by johnpatrick9** [comment]
Okay but it seemed to working fine few days back and the latest release of simple torrent was 15 days ago and weren't you using the same version before so why didn't it stop uploading to gdrive then and now all of sudden it stopped and why we should install an old version

P.S I apologize in advance if this in anyway annoying to you and I do appreciate it that you have created such a good repository again sorry @biplobsd

**Comment by biplobsd** [comment]
You know something. I reviewed source code but i can't figure out.?
@johnpatrick9

**Comment by johnpatrick9** [comment]
I am sorry but I didn't get what you are trying to say and I guess you have changed the script lines somewhere that's why it seems to be preventing the upload to gdrive and all of this just a guess,if you don't mind in me advicing you could check the recent versions where you've changed the repository
@biplobsd
